### ISSUE TITLE
NPE crash when placing transportation cart

### ISSUE THREAD

**Issue by xAlicatt** [MennoMax/astikor-carts#26]
crashreport: https://paste.dimdev.org/qoyihanego.rb

**Comment by MennoMax** [comment]
Sorry, missed a @SideOnly(Side.CLIENT) when changing the order of fields, thanks for reporting this.

**Comment by MennoMax** [comment]
Fixed by https://github.com/MennoMax/astikor-carts/commit/1c435984860671ac5a264e07c982ffd9859b55ee, will now release the update on CurseForge.
