### ISSUE TITLE
[suggestion] Villagers on horses with carts

### ISSUE THREAD

**Issue by koravel** [MennoMax/astikor-carts#27]
Villagers can travel with some stuff in carts(like dungeon chests) or caravan(with guards or smthg).
Or Villagers working on fields with pow cart(on horses, of course :) ).
And a config options for this, like:
-on/off
-what kinds of carts allowed
-etc.
Hmm after all that I wrote here, it sounds like a idea for new mod, compatible with this))))

**Comment by MennoMax** [comment]
Villagers can't sit in vanilla minecraft, which makes it difficult to have them ride a horse. This definitely would be something for a seperate mod, so I will close this issue.

But thank you for your suggestion :)
