### ISSUE TITLE
Helicopter cart glitch

### ISSUE THREAD

**Issue by MineCrak** [MennoMax/astikor-carts#28]
Hello. I am using version "astikorcarts-1.12.2-0.1.2.6" of your mod on my Forge 2768 server and a player "TwistedZero" has discovered a "Trick" that can be done with your Cart and Transportation Cart that allows players to fly them up like a Helicopter for one-way trips into the sky. Using the Transport Cart they can even take another passenger into the sky with them. Now I have several carts littering the sky for Elytras to crash into, heh. 

The main thing that allows this to happen is that I added "minecraft:player" to the "canPull" fields of the config file. I did that to simulate the behavior of my old Cart Mod and to allow greater versatility of use in some of the servers environs. 

To Reproduce: 

1. Add "minecraft:player" to the "canPull" fields of the config file.
2. Pull the cart.
3. Enter the cart while pulling it. 

The following is TwistedZero's theory of why this happens:

"when you are riding an entity the cart will match your Y coordinate, and when riding the cart you are slightly above the cart so the cart moves up to match your Y coord but you keep going up because you are sitting on the cart...".

He also made a video of this being done. In the video he is wearing an Elytra but he tells me that it isn't involved in any way and that he has tested this without wearing an Elytra and the same thing still happens:

https://www.youtube.com/watch?v=N2AVx7gT58I

**Comment by MineCrak** [comment]
One reason that this glitch is of even greater concern to me than it otherwise usually would be is that this is a Cubic Chunks server. So a player could use this glitch then go AFK for hours generating region files while it climbs towards the +1 billion block high top of the world. ;)

**Comment by MennoMax** [comment]
Thanks for reporting this, shouldn't be too hard to fix. :)

**Comment by MennoMax** [comment]
Fixed it, will now upload the file to curseforge.

**Comment by MineCrak** [comment]
Thanks!
