### ISSUE TITLE
Biomes O' Plenty Grass / dirt types

### ISSUE THREAD

**Issue by NekoJess88** [MennoMax/astikor-carts#29]
I've found that it is not possible to plow Loamy, and silty grass / dirt and am assuming the other BOP dirt and grass types have similar issues. The mod config does not have an area where I can add block types for plowing either. Just wondering if this is intended or something to be addressed later~

Other than that, I love your mod! Thank you for putting forth the effort to make it! It really is a wonderful addition to any Minecraft play through~!

**Comment by MennoMax** [comment]
Thanks, I will definitely adress this in 1.14, once a stable forge version hase been released.

**Comment by NekoJess88** [comment]
Is it possible to add support for it in 1.12 as well?

**Comment by MennoMax** [comment]
closed by 089231e9228849e9e8414b7f6589fa78790d64d7

A 1.12.2 port might follow after the 1.14.4 release.
