### ISSUE TITLE
Visual changes for better identifying different kinds of carts

### ISSUE THREAD

**Issue by sepsol** [MennoMax/astikor-carts#39]
I sometimes forget which is which, specially for 'carts' and 'transportation carts'. It would be great if there was a significant visual difference between them. I suggest having a chest on normal 'carts' :)

**Comment by MennoMax** [comment]
The latest 1.14.4 version should already have new item textures that shows a chest for the cargo cart. Is this not the case?

**Comment by SepSol** [comment]
This is how they both look like in 1.14.4:

![2019-10-23_11 27 53](https://user-images.githubusercontent.com/47871887/67371435-3f219180-f589-11e9-9742-e1d4c125286b.png)

If you meant their icons in the inventory, yes they look different. The Cart one has a chest in it. But when placing them down there is almost no difference at all, except the back part being open in one of them (which is hard to remember which is which). I wish the Cart one was like these boats and Minecarts:

![2019-10-23_11 34 18](https://user-images.githubusercontent.com/47871887/67371551-6b3d1280-f589-11e9-9818-93f1d63c1919.png)

**Comment by MennoMax** [comment]
I won't add a simple chest to the back of the cargo cart. I made it with medieval rp servers in mind, which can make good use of the visual representation depending on how much cargo is in the cart. The mob cart is thicker and slightly higher, the cargo cart has individual boards on the sides. Hope you will get used to them at some point ^^

**Comment by SepSol** [comment]
You could add an option in the config maybe?! That could help for those who prefer the chests being on the carts to match the other cart-type stuff in minecraft! It's more intuitive for newbies like me.

**Comment by pau101** [comment]
This issue is now resolved given new 1.16 cart models, if a chest is put in the inventory of a supply cart it will display visually.

![image](https://user-images.githubusercontent.com/5201207/109139036-e24f6180-770f-11eb-84be-64351c8de109.png)
