### ISSUE TITLE
 Add support for Public GUI Announcement mod

### ISSUE THREAD

**Issue by SepSol** [MennoMax/astikor-carts#40]
When using different Cart menus, no GUI shows up. Please add support for [PGA](https://www.curseforge.com/minecraft/mc-mods/public-gui-announcement) mod. Thanks.

**Comment by MennoMax** [comment]
You already opened an issue related to this, even answered to my response.

Duplicate of #38

**Comment by SepSol** [comment]
Sorry, I'm adding issues all over the place these days! sometimes I forget :)
