### ISSUE TITLE
korean language file for 1.0.1 is here!

### ISSUE THREAD

**Issue by MilkissWhite** [MennoMax/astikor-carts#43]
small translation.

[ko_kr.zip](https://github.com/MennoMax/astikor-carts/files/4271101/ko_kr.zip)

thx for good mod

**Comment by pau101** [comment]
Thank you for your contribution! The next release will include these.

**Comment by pau101** [comment]
I noticed "Distance by Cart" was not translated. This is used in the "Statistics" screen of the game:

![2020-02-29_21 11 39](https://user-images.githubusercontent.com/5201207/75620630-d1413400-5b3f-11ea-8a08-528a98ed14e2.png)

So I have used "수레 타고 이동한 거리", based on similar statistics.

**Comment by MilkissWhite** [comment]
thank you. I didn't know where that line used. and I think "수레 타고 이동한 거리" is best choice!
