### ISSUE TITLE
Game crashes when skeleton trap is spawned

### ISSUE THREAD

**Issue by MennoMax** [MennoMax/astikor-carts#45]
This issue has been reported [on curseforge](https://www.curseforge.com/minecraft/mc-mods/astikorcarts?comment=321).

When a horse trap is triggered, the game crashes.

Simply join a world and use /summon skeleton_horse ~ ~ ~ {SkeletonTrap:1} to trigger it. I confirmed the crash with only astikorcarts v1.0.1 installed.

[Crash Log](https://pastebin.com/qb3qU1qQ)

**Comment by pau101** [comment]
Fixed in [1.0.2](https://www.curseforge.com/minecraft/mc-mods/astikorcarts/files/2899662)
