### ISSUE TITLE
Game crashes when plow disconnects from horse

### ISSUE THREAD

**Issue by MennoMax** [MennoMax/astikor-carts#46]
This issue has been reported [on curseforge](https://www.curseforge.com/minecraft/mc-mods/astikorcarts?comment=321).

When a plow is disconnected without the action key (by getting a block between the plow and the pulling entity), the game crashes.

[Crash Log](https://pastebin.com/jh6WNsTb)

**Comment by pau101** [comment]
Fixed in [1.0.2](https://www.curseforge.com/minecraft/mc-mods/astikorcarts/files/2899662)
