### ISSUE TITLE
Optifine crash

### ISSUE THREAD

**Issue by MennoMax** [MennoMax/astikor-carts#47]
This issue has been reported by curseforge user gazeluttza in my dms.

> Hello,
> I'm trying to use shaders/optifine with your mod and I've encountered the below error:
> 
> https://pastebin.com/iUv45MhV

**Comment by pau101** [comment]
OptiFine 1.15.2 is not compatible with forge. This is specified in 1.15.2_HD_U_G1_pre9 changelog.
