### ISSUE TITLE
Compat w/ Horse Genetics

### ISSUE THREAD

**Issue by WenXin20** [MennoMax/astikor-carts#48]
The mod [Realistic Horse Genetics](https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics)  replaces horses with it's own custom horses, but Astikor carts cannot be attached to them.

Could compat for this be added?

**Comment by pau101** [comment]
Our configuration file is located at "config/astikorcarts-common.toml" You can add any entities to the "pullEntities" list. The mod page you linked's FAQ conveniently explains what is needed to have their horses be recognized by our mod.

**Comment by WenXin20** [comment]
Oh, I didn't realize that, thanks!

**Comment by pau101** [comment]
Happy carting!
