### ISSUE TITLE
Horse cart multiplayer bug 

### ISSUE THREAD

**Issue by Fireworkstars46** [MennoMax/astikor-carts#51]
Whenever my bother hosts a lan SP world and I join him, the game crashes when I move the carts and my bother leaves my area (out of his render distance) but fine if the host does it.

**Comment by pau101** [comment]
I'll need the crash report in order to troubleshoot the issue. They are generated in the `.minecraft/crashreports` folder.

**Comment by Fireworkstars46** [comment]
Crash report or log?

**Comment by pau101** [comment]
Crash report

**Comment by Fireworkstars46** [comment]
https://cdn.fbsbx.com/v/t59.2708-21/109308452_2355800241390513_2424427876254423314_n.txt/crash-2020-07-14_16.50.04-client.txt?_nc_cat=109&_nc_sid=0cab14&_nc_oc=AQm-G-PlsNJ7HVLolOuAnCljbHfhw3wJt1FOQ1W9-vaQrCLeJEXZcM8LdHrF9KUK7L4smFY4tbI6Cv9F_gB0nxVy&_nc_ht=cdn.fbsbx.com&oh=9efa9aed15de75b7ddaf6f74f63c2635&oe=5F0FB22D&dl=1

**Comment by Fireworkstars46** [comment]
This one is 1.14.4 one 

https://cdn.fbsbx.com/v/t59.2708-21/109313103_283048779681214_6827378058912211835_n.txt/crash-2020-07-14_17.23.57-client.txt?_nc_cat=106&_nc_sid=0cab14&_nc_oc=AQn1w3twPtsd2oZ2kWg--CLZ12QghUDxoH6OXYB6nSPouTlrRAsecmyzszQPEmM2D8-B6OL5YEib4uG7KAI3D-X9&_nc_ht=cdn.fbsbx.com&oh=2dbf40a2adb82d55ae24f9b010068764&oe=5F0FCA79&dl=1

**Comment by pau101** [comment]
Thank you a fix will be on the way.

**Comment by pau101** [comment]
Now fixed in 1.0.3: [1.15.2](https://www.curseforge.com/minecraft/mc-mods/astikorcarts/files/3005020), [1.14.4](https://www.curseforge.com/minecraft/mc-mods/astikorcarts/files/2899660)
