### ISSUE TITLE
AstikorCarts 1.1.1 fails on startup

### ISSUE THREAD

**Issue by enduum** [MennoMax/astikor-carts#62]
AstikorCarts 1.1.1
Minecraft 1.16.5
Forge 36.0.42
[[link to crash report]](https://pastebin.com/ac18bquq)
[[link to screenshot]](https://i.postimg.cc/6p4bc7Gs/astikorcarts-error.png)

**Comment by Zothen1973** [comment]
I only tested on server side so far, but I can confirm the crash.

Same versions as above.

[crash-2021-02-25_08.41.23-fml.txt](https://github.com/MennoMax/astikor-carts/files/6041263/crash-2021-02-25_08.41.23-fml.txt)

**Comment by pau101** [comment]
Okay you can redownload [AstikorCarts 1.1.1](https://www.curseforge.com/minecraft/mc-mods/astikorcarts/files/3216457), a build issue which I've never encountered before occurred.
