### ISSUE TITLE
Attaching carts to horses to pull???

### ISSUE THREAD

**Issue by NotsoGoodModder** [MennoMax/astikor-carts#63]
How do you attach horses to carts? The action key isn't working for it.

**Comment by pau101** [comment]
You ride a horse and then use the action key with a cart close by.

**Comment by NotsoGoodModder** [comment]
I have done this many times and it still doesn’t work. Even uninstalled and reinstalled the mod. (May be my sleep deprived self though lol)

**Comment by pau101** [comment]
Have you touched the config?

**Comment by NotsoGoodModder** [comment]
No I have not. Do I need to? :?

**Comment by NotsoGoodModder** [comment]
So I've figured out my problem. Regular horses work but the horses from Realistic horse genetics do not work.

**Comment by pau101** [comment]
Yes those need to be added to configuration unless you're using the latest 1.16 releases which then they should automatically work.

**Comment by NotsoGoodModder** [comment]
I'm using 1.15.2 How would I add them? Like the title????? If that makes sense. ^^'

**Comment by pau101** [comment]
Edit the astikor carts config file and add horse_colors:horse_felinoid to the lists of entities that can pull the carts.

**Comment by NotsoGoodModder** [comment]
Thank you!
