### ISSUE TITLE
XP tap issue on nether

### ISSUE THREAD

**Issue by sb555** [MennoMax/astikor-carts#72]
When returning to a blaze grinder in the nether, nothing happens when you open the xp tap. You have to break it and replace it, then it will work. Every time.

**Comment by MennoMax** [comment]
Is this issue related to AstikorCarts? You seem to have stumbled across the wrong repository, were you by any chance looking for this one? https://github.com/vadis365/Mob-Grinding-Utils/issues

Thanks for reporting it anyway ^^

**Comment by sb555** [comment]
Oh, yes I meant to post it there. Guess I wasn't paying attention, sorry!
