### ISSUE TITLE
Users able to access cart inventory from far away

### ISSUE THREAD

**Issue by Pingu-Pox** [MennoMax/astikor-carts#81]
Minecraft 1.12.2
astikorcarts-1.12.2-0.1.2.7.jar
Forge 1.12.2 - 14.23.5.2860

Had a user1 open a <astikorcarts:cargocart> on a server, and had user2 ride away with the cart. As long as user1 keeps the inventory open, they are able to essentially remote-trade with those who access the cart's inventory at it's new location.

**Comment by MennoMax** [comment]
This bug has already been fixed in the most recent version.
https://www.curseforge.com/minecraft/mc-mods/astikorcarts/files/3517236

Closing.
