### ISSUE TITLE
Porting mod to Fabric?

### ISSUE THREAD

**Issue by perdakovich** [MennoMax/astikor-carts#91]
It's quite sad that horses receive such minimal attention. I like horse mods in general  (although only a select few, including yours, appeal to my tastes, for example I don't like SWEM)

However, Astikor Carts are currently unavailable on Fabric. Would it be possible for someone to port it?

Thank you!

**Comment by jmb05** [comment]
Hey, just wanted to inform you and anyone interested that I have ported AstikorCarts to Fabric. It is called NiftyCarts and is available on [Modrinth](https://modrinth.com/mod/niftycarts), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/niftycarts) and [GitHub](https://github.com/jmb05/nifty-carts).

**Comment by perdakovich** [comment]
haven't tested it yet, but looks amazing! thank you for your efforts @jmb05 
I like the formatting of the mod page, you showed everything clearly! I followed it on Modrinth  :+1:
